concommand.Add("tttrw_crosshair_menu", function()
	local frame = vgui.Create("DFrame")
	frame:SetPos(ScrW()/2-400,ScrH()/2-250)
	frame:SetSize(800,500)
	frame:SetTitle("Crosshair Menu")
	frame:SetVisible(true)
	frame:SetDraggable(true)
	frame:ShowCloseButton(true)
	frame:MakePopup()

	local crosshair = vgui.Create("ttt_crosshairs", frame)
	crosshair:SetPos(25,0)
	crosshair:SetSize(400,475)

	local col = vgui.Create("DColorMixer", frame)
	col:SetPos(450,50)
	col:SetSize(300,150)
	col:SetPalette(true)
	col:SetWangs(true)
	col:SetAlphaBar(false)
	col:SetColor(Color(GetConVar("tttrw_crosshair_color_r"):GetInt(),GetConVar("tttrw_crosshair_color_g"):GetInt(),GetConVar("tttrw_crosshair_color_b"):GetInt()))
	col:SetConVarR("tttrw_crosshair_color_r")
	col:SetConVarG("tttrw_crosshair_color_g")
	col:SetConVarB("tttrw_crosshair_color_b")

	local thick = vgui.Create("DNumSlider", frame)
	thick:SetPos(450,200)
	thick:SetSize(300,50)
	thick:SetText("Thickness")
	thick:SetMin(0)
	thick:SetMax(30)
	thick:SetDecimals(0)
	thick:SetConVar("tttrw_crosshair_thickness")

	local len = vgui.Create("DNumSlider", frame)
	len:SetPos(450,240)
	len:SetSize(300,50)
	len:SetText("Length")
	len:SetMin(0)
	len:SetMax(100)
	len:SetDecimals(0)
	len:SetConVar("tttrw_crosshair_length")

	local gap = vgui.Create("DNumSlider", frame)
	gap:SetPos(450,280)
	gap:SetSize(300,50)
	gap:SetText("Gap")
	gap:SetMin(0)
	gap:SetMax(50)
	gap:SetDecimals(0)
	gap:SetConVar("tttrw_crosshair_gap")

	local op = vgui.Create("DNumSlider", frame)
	op:SetPos(450,320)
	op:SetSize(300,50)
	op:SetText("Opacity")
	op:SetMin(0)
	op:SetMax(255)
	op:SetDecimals(0)
	op:SetConVar("tttrw_crosshair_opacity")

	local outop = vgui.Create("DNumSlider", frame)
	outop:SetPos(450,360)
	outop:SetSize(300,50)
	outop:SetText("Outline Opacity")
	outop:SetMin(0)
	outop:SetMax(255)
	outop:SetDecimals(0)
	outop:SetConVar("tttrw_crosshair_outline_opacity")

	local dot = vgui.Create("DNumSlider", frame)
	dot:SetPos(450,400)
	dot:SetSize(300,50)
	dot:SetText("Dot Size")
	dot:SetMin(0)
	dot:SetMax(20)
	dot:SetDecimals(0)
	dot:SetConVar("tttrw_crosshair_dot_size")

	local dotop = vgui.Create("DNumSlider", frame)
	dotop:SetPos(450,440)
	dotop:SetSize(300,50)
	dotop:SetText("Dot Opacity")
	dotop:SetMin(0)
	dotop:SetMax(255)
	dotop:SetDecimals(0)
	dotop:SetConVar("tttrw_crosshair_dot_opacity")

	local reset = vgui.Create("DButton", frame)
	reset:SetPos(175,425)
	reset:SetSize(100,50)
	reset:SetText("Reset")
	function reset:DoClick()
		col:SetColor(Color(232,80,94))
		thick:SetValue(2)
		len:SetValue(7)
		gap:SetValue(3)
		op:SetValue(255)
		outop:SetValue(255)
		dot:SetValue(0)
		dotop:SetValue(255)
	end
end)